version: '3.5'

services:
  mongodb:
    container_name: db
    image: mongo:6.0
    ports:
      - ${MONGO_INITDB_PORT}:27017
    environment:
      MONGO_INITDB_HOST: ${MONGO_INITDB_HOST}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
