version: '3.5'

services:
  mongodb:
    container_name: db
    image: mongo:6.0
    ports:
      - ${MONGO_INITDB_PORT}:27017
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - metabase_network
    environment:
      MONGO_INITDB_HOST: ${MONGO_INITDB_HOST}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  
  metabase:
    container_name: metabase
    image: metabase/metabase
    ports:
      - 3000:3000
    environment:
      - MB_DB_FILE=${MB_DB_FILE}
    volumes:
      - ./data/metabase:/metabase-data
    networks:
      - metabase_network
    depends_on:
      - mongodb

networks:
  metabase_network:
    driver: bridge
