name: tests

on: 
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          context: "{{defaultContext}}:/"
          file: ./docker/application.Dockerfile
      
      - name: Copiar arquivo para .env
        run: |
          cp .env.example .env

      - name: Habilitando a execução do script de testes
        run: |
          chmod +x ./scripts/poetry_tests.sh
      
      - name: Levantar  o container da aplicação e rodar os testes
        run: |
          docker build -t application-testes -f "docker/application.Dockerfile" .
          docker run application-testes sh -c "./scripts/poetry_tests.sh"
          